-- Seed Data for McCrackan Roll-Off Service
-- All prices in cents

-- ============================================
-- ADMIN USER SETUP
-- ============================================
-- Creates admin user: gmurin@icloud.com / gmurin08
-- ============================================

-- Insert admin user into auth.users
INSERT INTO auth.users (
  id,
  instance_id,
  email,
  encrypted_password,
  email_confirmed_at,
  raw_app_meta_data,
  raw_user_meta_data,
  aud,
  role,
  created_at,
  updated_at,
  confirmation_token,
  recovery_token,
  email_change,
  email_change_token_new,
  email_change_token_current,
  phone,
  phone_change,
  phone_change_token,
  reauthentication_token,
  is_sso_user,
  is_anonymous
)
VALUES (
  'd906a864-e7c2-4b1f-a0b8-3edcb55cd5a4',
  '00000000-0000-0000-0000-000000000000',
  'gmurin@icloud.com',
  -- password: gmurin08 (bcrypt hash generated by GoTrue)
  '$2a$10$0d75PD.1xi22o8dO74CnlO3pgQWOrqn74F6/QVUm7Mm2UtF03p4dy',
  NOW(),
  '{"provider": "email", "providers": ["email"]}',
  '{"full_name": "Admin User"}',
  'authenticated',
  'authenticated',
  NOW(),
  NOW(),
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  FALSE,
  FALSE
);

-- Insert identity record for the user
INSERT INTO auth.identities (
  id,
  user_id,
  provider_id,
  provider,
  identity_data,
  last_sign_in_at,
  created_at,
  updated_at
)
VALUES (
  'd906a864-e7c2-4b1f-a0b8-3edcb55cd5a4',
  'd906a864-e7c2-4b1f-a0b8-3edcb55cd5a4',
  'gmurin@icloud.com',
  'email',
  '{"sub": "d906a864-e7c2-4b1f-a0b8-3edcb55cd5a4", "email": "gmurin@icloud.com", "email_verified": true}',
  NOW(),
  NOW(),
  NOW()
);

-- ============================================
-- BUSINESS
-- ============================================

INSERT INTO businesses (id, name, phone, email, address)
VALUES (
  '00000000-0000-0000-0000-000000000001',
  'McCrackan Roll-Off Service',
  '412-965-2791',
  'gmurin@icloud.com',
  '1555 Oakdale Road, Oakdale, PA 15071'
);

-- Link user as business owner (must come after business is created)
INSERT INTO business_users (id, business_id, user_id, role)
VALUES (
  '2007dcc9-274d-45d5-a4d7-82feeb35320b',
  '00000000-0000-0000-0000-000000000001',
  'd906a864-e7c2-4b1f-a0b8-3edcb55cd5a4',
  'owner'
);

-- ============================================
-- BUSINESS SETTINGS
-- ============================================

INSERT INTO business_settings (business_id, settings)
VALUES (
  '00000000-0000-0000-0000-000000000001',
  '{
    "quote_expiration_days": 7,
    "notification_emails": ["gmurin@icloud.com"],
    "terms_text": "By proceeding, you agree to our rental terms and conditions. Dumpsters must be accessible for delivery and pickup. No hazardous materials allowed.",
    "default_included_days": 3
  }'::jsonb
);

-- ============================================
-- SERVICE AREA
-- Polygon covering roughly 1 hour from Oakdale, PA (40.3985, -80.1848)
-- Covers: Pittsburgh metro, parts of WV, parts of OH
-- ============================================

INSERT INTO service_areas (business_id, name, polygon, active)
VALUES (
  '00000000-0000-0000-0000-000000000001',
  'Greater Pittsburgh Area',
  '{
    "type": "Polygon",
    "coordinates": [[
      [-80.9, 40.9],
      [-79.5, 40.9],
      [-79.3, 40.6],
      [-79.4, 40.1],
      [-79.8, 39.8],
      [-80.5, 39.7],
      [-80.9, 39.9],
      [-81.0, 40.3],
      [-80.9, 40.9]
    ]]
  }'::jsonb,
  TRUE
);

-- ============================================
-- PRICING RULES
-- All prices in cents
-- 3 days included, $25/day extra
-- ============================================

-- 10 Yard Dumpster - $350, 1 ton included, $100/ton overage
INSERT INTO pricing_rules (
  business_id, waste_type, dumpster_size,
  base_price, delivery_fee, haul_fee,
  included_days, extra_day_fee,
  included_tons, overage_per_ton,
  public_notes, active
)
VALUES (
  '00000000-0000-0000-0000-000000000001',
  'household_trash',
  10,
  35000,  -- $350.00
  0,
  0,
  3,
  2500,   -- $25.00/day
  1.00,
  10000,  -- $100.00/ton
  'Perfect for small cleanouts, single room renovations, or garage cleanups. Holds about 3 pickup truck loads.',
  TRUE
),
(
  '00000000-0000-0000-0000-000000000001',
  'construction_debris',
  10,
  35000,  -- $350.00
  0,
  0,
  3,
  2500,   -- $25.00/day
  1.00,
  10000,  -- $100.00/ton
  'Perfect for small renovations or construction cleanups. Holds about 3 pickup truck loads.',
  TRUE
);

-- 15 Yard Dumpster - $399, 1 ton included, $100/ton overage
INSERT INTO pricing_rules (
  business_id, waste_type, dumpster_size,
  base_price, delivery_fee, haul_fee,
  included_days, extra_day_fee,
  included_tons, overage_per_ton,
  public_notes, active
)
VALUES (
  '00000000-0000-0000-0000-000000000001',
  'household_trash',
  15,
  39900,  -- $399.00
  0,
  0,
  3,
  2500,   -- $25.00/day
  1.00,
  10000,  -- $100.00/ton
  'Great for medium projects like basement cleanouts or deck removals. Holds about 4-5 pickup truck loads.',
  TRUE
),
(
  '00000000-0000-0000-0000-000000000001',
  'construction_debris',
  15,
  39900,  -- $399.00
  0,
  0,
  3,
  2500,   -- $25.00/day
  1.00,
  10000,  -- $100.00/ton
  'Ideal for kitchen/bath remodels or roofing projects. Holds about 4-5 pickup truck loads.',
  TRUE
);

-- 20 Yard Dumpster - $500, 2 tons included, $100/ton overage
INSERT INTO pricing_rules (
  business_id, waste_type, dumpster_size,
  base_price, delivery_fee, haul_fee,
  included_days, extra_day_fee,
  included_tons, overage_per_ton,
  public_notes, active
)
VALUES (
  '00000000-0000-0000-0000-000000000001',
  'household_trash',
  20,
  50000,  -- $500.00
  0,
  0,
  3,
  2500,   -- $25.00/day
  2.00,
  10000,  -- $100.00/ton
  'Best for larger home cleanouts, moving projects, or multi-room renovations. Holds about 6-7 pickup truck loads.',
  TRUE
),
(
  '00000000-0000-0000-0000-000000000001',
  'construction_debris',
  20,
  50000,  -- $500.00
  0,
  0,
  3,
  2500,   -- $25.00/day
  2.00,
  10000,  -- $100.00/ton
  'Perfect for new construction, major renovations, or demolition projects. Holds about 6-7 pickup truck loads.',
  TRUE
);

-- ============================================
-- SAMPLE DUMPSTERS (INVENTORY)
-- ============================================

INSERT INTO dumpsters (business_id, unit_number, size, status, notes)
VALUES
  ('00000000-0000-0000-0000-000000000001', 'D10-001', 10, 'available', NULL),
  ('00000000-0000-0000-0000-000000000001', 'D10-002', 10, 'available', NULL),
  ('00000000-0000-0000-0000-000000000001', 'D15-001', 15, 'available', NULL),
  ('00000000-0000-0000-0000-000000000001', 'D15-002', 15, 'available', NULL),
  ('00000000-0000-0000-0000-000000000001', 'D15-003', 15, 'available', NULL),
  ('00000000-0000-0000-0000-000000000001', 'D20-001', 20, 'available', NULL),
  ('00000000-0000-0000-0000-000000000001', 'D20-002', 20, 'available', NULL);
